name: first workflow on github actions
on:
  push:
    branches: 
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a message
        run: echo "hello this is my 1st workflow"
